
package projectchatsocketsjava;

import javax.swing.JButton;

public class accueil extends javax.swing.JPanel {

    /**
     * Creates new form WelcomePanel
     */
    public accueil() {
        initComponents();
    }

    public JButton getBtLogin_welcome() {
        return btLogin_welcome;
    }

    public JButton getBtSignUp_welcome() {
        return btSignUp_welcome;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btSignUp_welcome = new javax.swing.JButton();
        btLogin_welcome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1920, 1020));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Blanc Bleu Icône de Flèche Voyage Logo (3) (2).png"))); // NOI18N

        btSignUp_welcome.setBackground(new java.awt.Color(255, 102, 102));
        btSignUp_welcome.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btSignUp_welcome.setForeground(new java.awt.Color(255, 255, 255));
        btSignUp_welcome.setText("S'inscrire");
        btSignUp_welcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSignUp_welcomeActionPerformed(evt);
            }
        });

        btLogin_welcome.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btLogin_welcome.setForeground(new java.awt.Color(255, 102, 102));
        btLogin_welcome.setText("Se connecter");
        btLogin_welcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogin_welcomeActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Blog-post (4).jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btLogin_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSignUp_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 790, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(334, 334, 334))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(545, 545, 545))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btLogin_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSignUp_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(408, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btSignUp_welcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSignUp_welcomeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btSignUp_welcomeActionPerformed

    private void btLogin_welcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogin_welcomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLogin_welcomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin_welcome;
    private javax.swing.JButton btSignUp_welcome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
